### ISSUE TITLE
W4M integration

### ISSUE THREAD

**Issue by pkrog** [workflow4metabolomics/isa2w4m#14]
- Use conda for requirements.
- Test with planemo.
- Publish to testtoolshed.
- Ask for installation on dev instance.

**Comment by pkrog** [comment]
Hi @lecorguille , this is the last tool to install for @sneumann, here are the links to the toolsheds:
<https://testtoolshed.g2.bx.psu.edu/view/prog/isa2w4m/e91327d6e034>
<https://toolshed.g2.bx.psu.edu/view/prog/isa2w4m/1883d5274962>

**Comment by lecorguille** [comment]
Can you replace your double quote `"` with `'` in the `<command >` block ?
 
See the [IUC best practices](https://galaxy-iuc-standards.readthedocs.io/en/latest/best_practices/tool_xml.html#command-formatting)

**Comment by pkrog** [comment]
Done. I've pushed the new version on the toolsheds.

**Comment by lecorguille** [comment]
Done
